routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('login');
});

Route::get('/dashboard', function () {
    return view('dashboard');
});


Auth::routes();

// Route::middleware(['auth','user-role:Admin'])->group(function()
Route::prefix('admin')->middleware(['auth', 'user-role:Admin'])->as('admin.')->group(function ()
    {
    Route::get("home",[App\Http\Controllers\HomeController::class, 'adminHome'])->name("home");

    Route::prefix('kelompok')->as('kelompok.')->group(function ()
    {
        Route::get("select",[App\Http\Controllers\UserManagement\KelompokController::class,'select'])->name('select');
        Route::resource("index",App\Http\Controllers\UserManagement\KelompokController::class);
    });

    Route::prefix('siswa')->as('siswa.')->group(function ()
    {
        Route::get("select",[App\Http\Controllers\UserManagement\SiswaController::class,'select'])->name('select');
        Route::resource("index",App\Http\Controllers\UserManagement\SiswaController::class);
    });

    Route::resource("guru",App\Http\Controllers\UserManagement\GuruController::class);
    Route::resource("kelas",App\Http\Controllers\UserManagement\KelasController::class);
    
    Route::prefix('materi')->as('materi.')->group(function ()
    {
        Route::get("dokumen/select",[App\Http\Controllers\Admin\Materi\DokumenController::class,'select'])->name('dokumen.select');
        Route::resource("dokumen",App\Http\Controllers\Admin\Materi\DokumenController::class);
        Route::get("youtube/select",[App\Http\Controllers\Admin\Materi\YoutubeController::class,'select'])->name('youtube.select');
        Route::resource("youtube",App\Http\Controllers\Admin\Materi\YoutubeController::class);
        
    });

    Route::prefix('exam')->as('exam.')->group(function ()
    {
        Route::resource("master",App\Http\Controllers\Admin\Exam\MasterController::class);
        Route::resource("question",App\Http\Controllers\Admin\Exam\QuestionController::class);
        Route::resource("event",App\Http\Controllers\Admin\Exam\EventController::class);
        Route::get("event-select",[App\Http\Controllers\Admin\Exam\EventController::class,'select'])->name('event.select');
        Route::resource("exam",App\Http\Controllers\Admin\Exam\ExamController::class);
        Route::get("exam-select",[App\Http\Controllers\Admin\Exam\ExamController::class,'select'])->name('exam.select');
    });
});

// Route Guru
Route::prefix('guru')->middleware(['auth', 'user-role:Guru'])->as('guru.')->group(function ()
{
    Route::get("home",[App\Http\Controllers\HomeController::class, 'guruHome'])->name("home");

    Route::prefix('exam')->as('exam.')->group(function ()
    {
        Route::resource("master",App\Http\Controllers\Guru\Exam\MasterController::class);
        Route::resource("question",App\Http\Controllers\Guru\Exam\QuestionController::class);
        Route::resource("event",App\Http\Controllers\Guru\Exam\EventController::class);
        Route::get("event-select",[App\Http\Controllers\Guru\Exam\EventController::class,'select'])->name('event.select');
        Route::resource("exam",App\Http\Controllers\Guru\Exam\ExamController::class);
        Route::get("exam-select",[App\Http\Controllers\Guru\Exam\ExamController::class,'select'])->name('exam.select');
    });

    Route::prefix('materi')->as('materi.')->group(function ()
    {
        Route::get("dokumen/select",[App\Http\Controllers\Guru\Materi\DokumenController::class,'select'])->name('dokumen.select');
        Route::resource("dokumen",App\Http\Controllers\Guru\Materi\DokumenController::class);
        Route::get("youtube/select",[App\Http\Controllers\Guru\Materi\YoutubeController::class,'select'])->name('youtube.select');
        Route::resource("youtube",App\Http\Controllers\Guru\Materi\YoutubeController::class);
    });
});
// Route Siswa
Route::prefix('siswa')->middleware(['auth', 'user-role:Siswa'])->as('siswa.')->group(function ()
{
    Route::get("home",[App\Http\Controllers\HomeController::class, 'siswaHome'])->name("home");
    Route::resource("exam",App\Http\Controllers\Siswa\ExamController::class);
    Route::get("exam-select",[App\Http\Controllers\Siswa\ExamController::class,'select'])->name('exam.select');

    Route::prefix('materi')->as('materi.')->group(function ()
    {
        Route::resource("dokumen",App\Http\Controllers\Siswa\Materi\DokumenController::class);
        Route::resource("youtube",App\Http\Controllers\Siswa\Materi\YoutubeController::class);
    });
});

app/Models/Materi/MateriDokumen.php
<?php

namespace App\Models\Materi;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use App\Models\UserManagement\Kelas;

class MateriDokumen extends Model
{
    use HasFactory;

    protected $fillable = [
        'kelas_id',
        'judul',
        'file',
        'deskripsi',
    ];
    public function kelas(){
        return $this->belongsTo(Kelas::class, 'kelas_id');
    }
}

app/Models/Materi/MateriYoutube.php
<?php

namespace App\Models\Materi;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use App\Models\UserManagement\Kelas;

class MateriYoutube extends Model
{
    use HasFactory;
    protected $fillable = [
        'kelas_id',
        'judul',
        'link',
    ];
    public function kelas(){
        return $this->belongsTo(Kelas::class, 'kelas_id');
    }
}

app/Http/Controllers/Admin/Materi/DokumenController.php
<?php

namespace App\Http\Controllers\Admin\Materi;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;

use App\Models\Materi\MateriDokumen;
use App\Models\UserManagement\Kelas;

class DokumenController extends Controller
{
    public function select()
    {
        $kelases = Kelas::orderBy('nama')->get();
        return view('admin.materi.dokumen.select',compact('kelases'));
    }

    public function index(Request $request)
    {
        $dokumens = MateriDokumen::where('kelas_id',$request->kelas_id)->get();
        return view('admin.materi.dokumen.index',compact('dokumens'))->with('i');
    }

    public function store(Request $request)
    {
        $file = $request->file('file');
        $new_name = rand().'.'.$file->getClientOriginalExtension();
        $file->move(public_path('dokumen/materi/'), $new_name);

        MateriDokumen::create([
            'kelas_id'  => $request->kelas_id,
            'judul'     => $request->judul,
            'file'      => $new_name,
            'deskripsi' => $request->deskripsi,
        ]);
        return back()->with('success','Data Materi Dokumen Berhasil Ditambah');
    }

    public function update(Request $request, $id)
    {
        $materi = MateriDokumen::find($id);
        $materi->update([
            'judul'     => $request->judul,
            'deskripsi' => $request->deskripsi,
        ]);

        if($request->has('file'))
        {
            $path = public_path('dokumen/materi/'.($materi->file));
            File::delete($path);

            $file = $request->file('file');
            $new_name = rand().'.'.$file->getClientOriginalExtension();
            $file->move(public_path('dokumen/materi/'), $new_name);
            $materi->update(['file' => $new_name]);
            
        }
        return back()->with('success','Data Materi Dokumen Berhasil Diubah');
    }

    public function destroy($id)
    {
        $materi = MateriDokumen::find($id);
        $path = public_path('dokumen/materi/'.($materi->file));
        File::delete($path);
        $materi->delete();
        return back()->with('success','Data Materi Dokumen Berhasil Dihapus');
    }
}

app/Http/Controllers/Admin/Materi/YoutubeController.php
<?php

namespace App\Http\Controllers\Admin\Materi;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

use App\Models\Materi\MateriYoutube;
use App\Models\UserManagement\Kelas;

class YoutubeController extends Controller
{
    public function select()
    {
        $kelases = Kelas::orderBy('nama')->get();
        return view('admin.materi.youtube.select',compact('kelases'));
    }

    public function index(Request $request)
    {
        $youtubes = MateriYoutube::where('kelas_id',$request->kelas_id)->get();
        return view('admin.materi.youtube.index',compact('youtubes'))->with('i');
    }

    public function store(Request $request)
    {
        $request->validate([
            'link' => 'required|starts_with:https://www.youtube.com/embed/',
        ],[
            'link.starts_with'      => 'Link yang dimasukkan tidak dapat disimpan. Harap masukkan link embed Youtube'
        ]);
        MateriYoutube::create([
            'kelas_id'  => $request->kelas_id,
            'judul'     => $request->judul,
            'link'      => $request->link,
        ]);
        return back()->with('success','Data Materi Youtube Berhasil Ditambah');
    }

    public function update(Request $request, $id)
    {
        MateriYoutube::find($id)->update([
            'judul'     => $request->judul,
            'link'      => $request->link,
        ]);
        return back()->with('success','Data Materi Youtube Berhasil Diubah');
    }

    public function destroy($id)
    {
        MateriYoutube::find($id)->delete();
        return back()->with('success','Data Materi Youtube Berhasil Dihapus');
    }
}

app/Http/Controllers/Guru/Materi/DokumenController.php
<?php

namespace App\Http\Controllers\Guru\Materi;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;

use App\Models\Materi\MateriDokumen;
use App\Models\UserManagement\Kelas;

class DokumenController extends Controller
{
    public function select()
    {
        $kelases = Kelas::orderBy('nama')->get();
        return view('guru.materi.dokumen.select',compact('kelases'));
    }

    public function index(Request $request)
    {
        $dokumens = MateriDokumen::where('kelas_id',$request->kelas_id)->get();
        return view('guru.materi.dokumen.index',compact('dokumens'))->with('i');
    }

    public function store(Request $request)
    {
        $file = $request->file('file');
        $new_name = rand().'.'.$file->getClientOriginalExtension();
        $file->move(public_path('dokumen/materi/'), $new_name);

        MateriDokumen::create([
            'kelas_id'  => $request->kelas_id,
            'judul'     => $request->judul,
            'file'      => $new_name,
            'deskripsi' => $request->deskripsi,
        ]);
        return back()->with('success','Data Materi Dokumen Berhasil Ditambah');
    }

    public function update(Request $request, $id)
    {
        $materi = MateriDokumen::find($id);
        $materi->update([
            'judul'     => $request->judul,
            'deskripsi' => $request->deskripsi,
        ]);

        if($request->has('file'))
        {
            $path = public_path('dokumen/materi/'.($materi->file));
            File::delete($path);

            $file = $request->file('file');
            $new_name = rand().'.'.$file->getClientOriginalExtension();
            $file->move(public_path('dokumen/materi/'), $new_name);
            $materi->update(['file' => $new_name]);
            
        }
        return back()->with('success','Data Materi Dokumen Berhasil Diubah');
    }

    public function destroy($id)
    {
        $materi = MateriDokumen::find($id);
        $path = public_path('dokumen/materi/'.($materi->file));
        File::delete($path);
        $materi->delete();
        return back()->with('success','Data Materi Dokumen Berhasil Dihapus');
    }
}

app/Http/Controllers/Guru/Materi/YoutubeController.php
<?php

namespace App\Http\Controllers\Guru\Materi;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

use App\Models\Materi\MateriYoutube;
use App\Models\UserManagement\Kelas;

class YoutubeController extends Controller
{
    public function select()
    {
        $kelases = Kelas::orderBy('nama')->get();
        return view('guru.materi.youtube.select',compact('kelases'));
    }

    public function index(Request $request)
    {
        $youtubes = MateriYoutube::where('kelas_id',$request->kelas_id)->get();
        return view('guru.materi.youtube.index',compact('youtubes'))->with('i');
    }

    public function store(Request $request)
    {
        $request->validate([
            'link' => 'required|starts_with:https://www.youtube.com/embed/',
        ],[
            'link.starts_with'      => 'Link yang dimasukkan tidak dapat disimpan. Harap masukkan link embed Youtube'
        ]);
        MateriYoutube::create([
            'kelas_id'  => $request->kelas_id,
            'judul'     => $request->judul,
            'link'      => $request->link,
        ]);
        return back()->with('success','Data Materi Youtube Berhasil Ditambah');
    }

    public function update(Request $request, $id)
    {
        MateriYoutube::find($id)->update([
            'judul'     => $request->judul,
            'link'      => $request->link,
        ]);
        return back()->with('success','Data Materi Youtube Berhasil Diubah');
    }

    public function destroy($id)
    {
        MateriYoutube::find($id)->delete();
        return back()->with('success','Data Materi Youtube Berhasil Dihapus');
    }
}

app/Http/Controllers/Siswa/Materi/DokumenController.php
<?php

namespace App\Http\Controllers\Siswa\Materi;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\File;

use App\Models\Materi\MateriDokumen;
use App\Models\UserManagement\Kelas;

class DokumenController extends Controller
{
    public function index(Request $request)
    {
        $dokumens = MateriDokumen::where('kelas_id',Auth::user()->kelas_id)->get();
        return view('siswa.materi.dokumen.index',compact('dokumens'))->with('i');
    }
}

app/Http/Controllers/Siswa/Materi/YoutubeController.php
<?php

namespace App\Http\Controllers\Siswa\Materi;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

use App\Models\Materi\MateriYoutube;
use App\Models\UserManagement\Kelas;

class YoutubeController extends Controller
{
    public function index(Request $request)
    {
        $youtubes = MateriYoutube::where('kelas_id',Auth::user()->kelas_id)->get();
        return view('siswa.materi.youtube.index',compact('youtubes'))->with('i');
    }

}

resources/views/guru/materi/youtube/index.blade.php
@extends('template.app')
@section('content')
    <div class="">
        <div class="page-title">
            <div class="title_left">
                <h4>Materi</h4>
            </div>
        </div>

        <div class="x_content bs-example-popovers">
           
        </div>
        <div class="clearfix"></div>
        <div class="row">
            <div class="col-md-12 col-sm-12 ">
                <div class="x_panel">
                <div class="x_title">
                    <h2>List Materi Youtube</h2>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="card-box" style="padding-right:10px">
                                <button  type="button"  class="btn btn-info" data-toggle="modal" data-target="#modal-lg" style="float:right;" >
                                <i class="fa fa-plus"></i> Tambah Materi
                                </button>
                            </div>
                        </div>
                        <div class="col-sm-12">
                            <div class="card-box table-responsive">
                                <table id="datatable" class="table table-striped table-bordered" style="width:100%">
                                    <thead>
                                        <tr>
                                            <th style="text-align: center;" width="5%">No</th>
                                            <th style="text-align: center;">Judul</th>
                                            <th style="text-align: center; width:24%">Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach ($youtubes as $youtube)
                                        <tr>
                                            <td style="text-align: center;">{{++$i}}</td>
                                            <td style="text-align: center;">{{$youtube->judul}}</td>
                                            <td style="text-align: center;">
                                                <div class="d-flex justify-content-between align-items-center">
                                                    <button type="button" class="btn btn-warning text-white"  data-toggle="modal" data-target="#modal-edit-lg{{$youtube->id}}"><i class="fa fa-pencil"></i> Ubah</button>
                                                    <button type="button" class="btn btn-secondary"  data-toggle="modal" data-target="#modal-edit-lg{{'youtube'.$youtube->id}}"><i class="	fa fa-play-circle"></i> Video</button>
                                                    <form action="{{route('guru.materi.youtube.destroy', $youtube->id)}}" method="POST">
                                                        @csrf
                                                        @method('DELETE')
                                                        <button type="submit" class="btn btn-danger"><i class="fa fa-trash"></i> Hapus</button>
                                                    </form>
                                                </div>
                                                                
                                            </td>
                                        </tr>                   
                                        @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <x-box-modal-large>
        @slot('title') Tambah Materi Youtube @endslot

        @slot('body')
        <form id="demo-form2" action="{{route('guru.materi.youtube.store')}}" method="POST" data-parsley-validate class="form-horizontal form-label-left">
            @csrf
            <div class="item form-group">
                <label class="col-form-label col-md-3 col-sm-3 label-align" for="nama">Judul <span class="required">*</span>
                </label>
                <div class="col-md-9 col-sm-9 ">
                    <input type="text" id="judul" name="judul" required="required" class="form-control ">
                </div>
            </div>
            <div class="item form-group">
                <label class="col-form-label col-md-3 col-sm-3 label-align" for="nama">Link Youtube <span class="required">*</span>
                </label>
                <div class="col-md-9 col-sm-9 ">
                    <input type="url" id="link" name="link" required="required" class="form-control ">
                </div>
            </div>
            <input type="hidden" name="kelas_id" value="{{app('request')->input('kelas_id')}}">
            <div class="ln_solid"></div>
            <div class="item form-group">
                <div class="col-md-12">
                    <button type="submit" class="btn btn-info"  style="float: right;">Submit</button>
                    <button type="button" class="btn btn-secondary"  style="float: right;" data-dismiss="modal">Close</button>
                </div>
            </div>
        </form>
        @endslot

    </x-box-modal-large>

    @foreach ($youtubes as $youtube)
        <x-box-modal-edit-large id="{{$youtube->id}}">
            @slot('title') Edit Materi youtube @endslot
            @slot('body')
            <form id="demo-form2" action="{{route('guru.materi.youtube.update',$youtube->id)}}" method="POST" data-parsley-validate class="form-horizontal form-label-left">
                @csrf
                @method('PUT')

                <div class="item form-group">
                    <label class="col-form-label col-md-3 col-sm-3 label-align" for="nama">Judul <span class="required">*</span>
                    </label>
                    <div class="col-md-9 col-sm-9 ">
                        <input type="link" id="judul" name="judul" required="required" class="form-control " value="{{$youtube->judul}}">
                    </div>
                </div>

                <div class="item form-group">
                    <label class="col-form-label col-md-3 col-sm-3 label-align" for="email">Link Youtube <span class="required">*</span>
                    </label>
                    <div class="col-md-9 col-sm-9 ">
                        <input type="url" id="link" name="link" required="required" class="form-control" value="{{$youtube->link}}">
                    </div>
                </div>
                <div class="ln_solid"></div>
                <div class="item form-group">
                    <div class="col-md-12">
                        <button type="submit" class="btn btn-info"  style="float: right;">Submit</button>
                        <button type="button" class="btn btn-secondary"  style="float: right;" data-dismiss="modal">Close</button>
                    </div>
                </div>
            </form>
            @endslot
        </x-box-modal-edit-large>
        
        <x-box-modal-edit-large id="{{'youtube'.$youtube->id}}">
            @slot('title') {{$youtube->judul}} @endslot
            @slot('body')
                <iframe id="video{{$youtube->id}}" width="100%" height="500px" src="{{$youtube->link}}" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
            @endslot
        </x-box-modal-edit-large>
    @endforeach
@endsection
@push('js')
    <script>
        $(document).ready(function(){
            $(".modal").on("hidden.bs.modal", function(){
                $(this).find('iframe').each(function(){
                    var src = $(this).attr('src');
                    $(this).attr('src',src);
                });
            });
        });
    </script>
@endpush

resources/views/guru/materi/youtube/select.blade.php
@extends('template.app')
@section('content')
<div class="col-md-6 col-sm-6  ">
    <div class="x_panel">
      <div class="x_title">
        <h2>Select Data Kelompok</h2>
        <ul class="nav navbar-right panel_toolbox">
          <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
          </li>
          <li><a class="close-link"><i class="fa fa-close"></i></a>
          </li>
        </ul>
        <div class="clearfix"></div>
      </div>
      <div class="x_content">

        <form id="demo-form2" action="{{route('guru.materi.youtube.index')}}" method="GET" data-parsley-validate class="form-horizontal form-label-left">
            @csrf
            <div class="item form-group">
                <label class="col-form-label col-md-3 col-sm-3 label-align" for="kelas_id">Kelas <span class="required">*</span>
                </label>
                <div class="col-md-9 col-sm-9 ">
                    <select name="kelas_id" id="kelas_id" class="form-control">
                        @foreach ($kelases as $kelas)
                            <option value="{{$kelas->id}}">{{$kelas->tingkatan}} {{$kelas->nama}}</option>
                        @endforeach
                    </select>
                </div>
            </div>
            <div class="ln_solid"></div>
            <div class="item form-group">
                <div class="col-md-12">
                    <button type="submit" class="btn btn-info"  style="float: right;">Submit</button>
                    <button type="button" class="btn btn-secondary"  style="float: right;" data-dismiss="modal">Close</button>
                </div>
            </div>
        </form>

      </div>
    </div>
  </div>
@endsection