routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('login');
});

Route::get('/dashboard', function () {
    return view('dashboard');
});


Auth::routes();

// Route::middleware(['auth','user-role:Admin'])->group(function()
Route::prefix('admin')->middleware(['auth', 'user-role:Admin'])->as('admin.')->group(function ()
    {
    Route::get("home",[App\Http\Controllers\HomeController::class, 'adminHome'])->name("home");

    Route::prefix('kelompok')->as('kelompok.')->group(function ()
    {
        Route::get("select",[App\Http\Controllers\UserManagement\KelompokController::class,'select'])->name('select');
        Route::resource("index",App\Http\Controllers\UserManagement\KelompokController::class);
    });

    Route::prefix('siswa')->as('siswa.')->group(function ()
    {
        Route::get("select",[App\Http\Controllers\UserManagement\SiswaController::class,'select'])->name('select');
        Route::resource("index",App\Http\Controllers\UserManagement\SiswaController::class);
    });

    Route::resource("guru",App\Http\Controllers\UserManagement\GuruController::class);
    Route::resource("kelas",App\Http\Controllers\UserManagement\KelasController::class);
    
    Route::prefix('materi')->as('materi.')->group(function ()
    {
        Route::get("dokumen/select",[App\Http\Controllers\Admin\Materi\DokumenController::class,'select'])->name('dokumen.select');
        Route::resource("dokumen",App\Http\Controllers\Admin\Materi\DokumenController::class);
        Route::get("youtube/select",[App\Http\Controllers\Admin\Materi\YoutubeController::class,'select'])->name('youtube.select');
        Route::resource("youtube",App\Http\Controllers\Admin\Materi\YoutubeController::class);
        
    });

    Route::prefix('exam')->as('exam.')->group(function ()
    {
        Route::resource("master",App\Http\Controllers\Admin\Exam\MasterController::class);
        Route::resource("question",App\Http\Controllers\Admin\Exam\QuestionController::class);
        Route::resource("event",App\Http\Controllers\Admin\Exam\EventController::class);
        Route::get("event-select",[App\Http\Controllers\Admin\Exam\EventController::class,'select'])->name('event.select');
        Route::resource("exam",App\Http\Controllers\Admin\Exam\ExamController::class);
        Route::get("exam-select",[App\Http\Controllers\Admin\Exam\ExamController::class,'select'])->name('exam.select');
    });
});

// Route Guru
Route::prefix('guru')->middleware(['auth', 'user-role:Guru'])->as('guru.')->group(function ()
{
    Route::get("home",[App\Http\Controllers\HomeController::class, 'guruHome'])->name("home");

    Route::prefix('exam')->as('exam.')->group(function ()
    {
        Route::resource("master",App\Http\Controllers\Guru\Exam\MasterController::class);
        Route::resource("question",App\Http\Controllers\Guru\Exam\QuestionController::class);
        Route::resource("event",App\Http\Controllers\Guru\Exam\EventController::class);
        Route::get("event-select",[App\Http\Controllers\Guru\Exam\EventController::class,'select'])->name('event.select');
        Route::resource("exam",App\Http\Controllers\Guru\Exam\ExamController::class);
        Route::get("exam-select",[App\Http\Controllers\Guru\Exam\ExamController::class,'select'])->name('exam.select');
    });

    Route::prefix('materi')->as('materi.')->group(function ()
    {
        Route::get("dokumen/select",[App\Http\Controllers\Guru\Materi\DokumenController::class,'select'])->name('dokumen.select');
        Route::resource("dokumen",App\Http\Controllers\Guru\Materi\DokumenController::class);
        Route::get("youtube/select",[App\Http\Controllers\Guru\Materi\YoutubeController::class,'select'])->name('youtube.select');
        Route::resource("youtube",App\Http\Controllers\Guru\Materi\YoutubeController::class);
    });
});
// Route Siswa
Route::prefix('siswa')->middleware(['auth', 'user-role:Siswa'])->as('siswa.')->group(function ()
{
    Route::get("home",[App\Http\Controllers\HomeController::class, 'siswaHome'])->name("home");
    Route::resource("exam",App\Http\Controllers\Siswa\ExamController::class);
    Route::get("exam-select",[App\Http\Controllers\Siswa\ExamController::class,'select'])->name('exam.select');

    Route::prefix('materi')->as('materi.')->group(function ()
    {
        Route::resource("dokumen",App\Http\Controllers\Siswa\Materi\DokumenController::class);
        Route::resource("youtube",App\Http\Controllers\Siswa\Materi\YoutubeController::class);
    });
});

app/Http/Controllers/Admin/Exam/EventController.php
<?php

namespace App\Http\Controllers\Admin\Exam;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Carbon\Carbon;

use App\Models\Exam\ExamMaster;
use App\Models\Exam\ExamEvent;
use App\Models\Exam\Exam;

class EventController extends Controller
{
    public function select()
    {
        return view('admin.exam.event-select');
    }
    public function index(Request $request)
    {
        $events = ExamEvent::whereYear('mulai',$request->year)->whereMonth('mulai',$request->month)->where('selesai','>=', Carbon::now())->orderBy('mulai')->get();
        $dones  = ExamEvent::whereYear('mulai',$request->year)->whereMonth('mulai',$request->month)->where('selesai','<', Carbon::now())->orderBy('mulai')->get();

        $masters = ExamMaster::orderBy('name')->get();
        return view('admin.exam.event',compact('events','dones','masters'))->with('i');
    }

    public function store(Request $request)
    {
        ExamEvent::create([
            'name'       => $request->name,
            'master_id'  => $request->master_id,
            'mulai'      => $request->mulai,
            'selesai'    => $request->selesai,
        ]);
        return back()->with('success','Data Event Berhasil Ditambah');
    }

    public function show($id){
        $reports = Exam::where('event_id',$id)->orderBy('score','desc')->get();
        return view('admin.exam.report',compact('reports'))->with('i');
    }

    public function update(Request $request, $id)
    {
        ExamEvent::find($id)->update([
            'name'       => $request->name,
            'master_id'  => $request->master_id,
            'mulai'      => $request->mulai,
            'selesai'    => $request->selesai,
        ]);
        return back()->with('success','Data Exam Event Berhasil Diubah');
    }

    public function destroy($id)
    {
        try {
            ExamEvent::find($id)->delete();
            return back()->with('success','Data Exam Event Berhasil Dihapus');
        } catch (\Throwable $th) {
            return back()->withErrors('Data Exam Event Tidak Dapat Dihapus');
        }
        
    }
}

app/Http/Controllers/Admin/Exam/ExamController.php
<?php

namespace App\Http\Controllers\Admin\Exam;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\Auth;

use App\Models\Exam\ExamEvent;
use App\Models\Exam\ExamQuestion;
use App\Models\Exam\Exam;

class ExamController extends Controller
{
    public function select()
    {
        return view('admin.exam.exam-select');
    }

    public function index(Request $request)
    {
        $events = ExamEvent::whereYear('mulai',$request->year)->whereMonth('mulai',$request->month)->where('selesai','>=', Carbon::now())->orderBy('mulai')->get();
        $dones  = ExamEvent::whereYear('mulai',$request->year)->whereMonth('mulai',$request->month)->where('selesai','<', Carbon::now())->orderBy('mulai')->get();
        return view('admin.exam.exam',compact('events','dones'))->with('i');
    }
    public function show($id)
    {
        $exams  = Exam::all();
        $event = ExamEvent::find($id);
        if($exams->where('user_id',Auth::user()->id)->where('event_id',$event->id)->count()!=0){
            return back()->withErrors('Gagal masuk ujian');
        }else{
            return view('admin.exam.mulai',compact('event'))->with('i');
        }
    }
    public function store(Request $request){
        $jawaban     = $request->jawaban;
        $soals       = $request->soal;
        $knc_jawaban = ExamEvent::find($request->event_id)->master->question->pluck('jawaban','id')->toArray();
        $score       = 0;
        foreach($soals as $key => $soal)
        {
            $score += $knc_jawaban[$soal] == $jawaban[$key]? 1 : 0;
        }
        Exam::create([
            'event_id' => $request->event_id,
            'user_id'  => Auth::user()->id,
            'score'    => $score/count($soals)*100,
        ]);
        return redirect('admin/exam/exam')->with('success','Data ujian berhasil disimpan');
    }
}

app/Http/Controllers/Admin/Exam/MasterController.php
<?php

namespace App\Http\Controllers\Admin\Exam;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

use App\Models\Exam\ExamMaster;

class MasterController extends Controller
{
    public function index()
    {
        $masters = ExamMaster::orderBy('name')->get();
        return view('admin.exam.master',compact('masters'))->with('i');
    }

    public function store(Request $request)
    {
        ExamMaster::create([
            'name'       => $request->name,
            'created_by' => Auth::user()->id,
        ]);
        return back()->with('success','Data Exam Master Berhasil Ditambah');
    }

    public function update(Request $request, $id)
    {
        ExamMaster::find($id)->update([
            'name'       => $request->name,
            'created_by' => Auth::user()->id,
        ]);
        return back()->with('success','Data Exam Master Berhasil Diubah');
    }

    public function destroy($id)
    {
        try {
            ExamMaster::find($id)->delete();
            return back()->with('success','Data Exam Master Berhasil Dihapus');
        } catch (\Throwable $th) {
            return back()->withErrors('Data Exam Master Tidak Dapat Dihapus');
        }
        
    }
}

app/Http/Controllers/Admin/Exam/QuestionController.php
<?php

namespace App\Http\Controllers\Admin\Exam;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

use App\Models\Exam\ExamQuestion;

class QuestionController extends Controller
{
    public function index(Request $request)
    {
        $questions = ExamQuestion::where('master_id',$request->master_id)->orderBy('id','desc')->get();
        return view('admin.exam.question',compact('questions'))->with('i');
    }

    public function store(Request $request)
    {
        ExamQuestion::create([
            'master_id' => $request->master_id,
            'pertanyaan' => $request->pertanyaan,
            'jawaban1'   => $request->jawaban1,
            'jawaban2'   => $request->jawaban2,
            'jawaban3'   => $request->jawaban3,
            'jawaban4'   => $request->jawaban4,
            'jawaban5'   => $request->jawaban5,
            'jawaban'    => $request->jawaban,
        ]);
        return back()->with('success','Data Pertanyan Berhasil Ditambah');
    }

    public function update(Request $request, $id)
    {
        ExamQuestion::find($id)->update([
            'pertanyaan' => $request->pertanyaan,
            'jawaban1'   => $request->jawaban1,
            'jawaban2'   => $request->jawaban2,
            'jawaban3'   => $request->jawaban3,
            'jawaban4'   => $request->jawaban4,
            'jawaban5'   => $request->jawaban5,
            'jawaban'    => $request->jawaban,
        ]);
        return back()->with('success','Data Exam Master Berhasil Diubah');
    }

    public function destroy($id)
    {
        ExamQuestion::find($id)->delete();
        return back()->with('success','Data Exam Master Berhasil Dihapus');
    }
}

app/Http/Controllers/Guru/Exam/EventController.php
<?php

namespace App\Http\Controllers\Guru\Exam;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Carbon;

use App\Models\Exam\ExamMaster;
use App\Models\Exam\ExamEvent;
use App\Models\Exam\Exam;

class EventController extends Controller
{
    public function select()
    {
        return view('guru.exam.event-select');
    }

    public function index(Request $request)
    {
        $events  = ExamEvent::whereYear('mulai',$request->year)->whereMonth('mulai',$request->month)->where('selesai','>=', Carbon::now())->orderBy('mulai')->whereHas('master',function($query){
            return $query->where('created_by',Auth::user()->id);
        })->orderBy('mulai')->get();
        $dones  = ExamEvent::whereYear('mulai',$request->year)->whereMonth('mulai',$request->month)->where('selesai','<', Carbon::now())->orderBy('mulai')->whereHas('master',function($query){
            return $query->where('created_by',Auth::user()->id);
        })->orderBy('mulai')->get();
        $masters = ExamMaster::where('created_by',Auth::user()->id)->orderBy('name')->get();
        return view('guru.exam.event',compact('events','dones','masters'))->with('i');
    }

    public function store(Request $request)
    {
        ExamEvent::create([
            'name'       => $request->name,
            'master_id'  => $request->master_id,
            'mulai'      => $request->mulai,
            'selesai'    => $request->selesai,
        ]);
        return back()->with('success','Data Exam Master Berhasil Ditambah');
    }

    public function show($id){
        $reports = Exam::where('event_id',$id)->orderBy('score','desc')->get();
        return view('guru.exam.report',compact('reports'))->with('i');
    }

    public function update(Request $request, $id)
    {
        ExamEvent::find($id)->update([
            'name'       => $request->name,
            'master_id'  => $request->master_id,
            'mulai'      => $request->mulai,
            'selesai'    => $request->selesai,
        ]);
        return back()->with('success','Data Exam Master Berhasil Diubah');
    }

    public function destroy($id)
    {
        ExamEvent::find($id)->delete();
        return back()->with('success','Data Exam Master Berhasil Dihapus');
    }
}

app/Http/Controllers/Guru/Exam/ExamController.php
<?php

namespace App\Http\Controllers\Guru\Exam;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Carbon;

use App\Models\Exam\ExamEvent;
use App\Models\Exam\ExamQuestion;
use App\Models\Exam\ExamMaster;
use App\Models\Exam\Exam;

class ExamController extends Controller
{
    public function select()
    {
        return view('guru.exam.exam-select');
    }
    
    public function index(Request $request)
    {
        $events = ExamEvent::whereYear('mulai',$request->year)->whereMonth('mulai',$request->month)->where('selesai','>=', Carbon::now())->orderBy('mulai')->whereHas('master',function($query){
            return $query->where('created_by',Auth::user()->id);
        })->get();
        $dones = ExamEvent::whereYear('mulai',$request->year)->whereMonth('mulai',$request->month)->where('selesai','<', Carbon::now())->orderBy('mulai')->whereHas('master',function($query){
            return $query->where('created_by',Auth::user()->id);
        })->get();
        return view('guru.exam.exam',compact('events','dones'))->with('i');
    }
    public function show($id)
    {
        $exams  = Exam::all();
        $event = ExamEvent::find($id);
        if($exams->where('user_id',Auth::user()->id)->where('event_id',$event->id)->count()!=0){
            return back()->withErrors('Gagal masuk ujian');
        }else{
            return view('guru.exam.mulai',compact('event'))->with('i');
        }
    }
    public function store(Request $request){
        $jawaban     = $request->jawaban;
        $soals       = $request->soal;
        $knc_jawaban = ExamEvent::find($request->event_id)->master->question->pluck('jawaban','id')->toArray();
        $score       = 0;
        foreach($soals as $key => $soal)
        {
            $score += $knc_jawaban[$soal] == $jawaban[$key]? 1 : 0;
        }
        Exam::create([
            'event_id' => $request->event_id,
            'user_id'  => Auth::user()->id,
            'score'    => $score/count($soals)*100,
        ]);
        return redirect('guru/exam/exam')->with('success','Data ujian berhasil disimpan');
    }
}

app/Http/Controllers/Guru/Exam/MasterController.php
<?php

namespace App\Http\Controllers\Guru\Exam;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

use App\Models\Exam\ExamMaster;

class MasterController extends Controller
{
    public function index()
    {
        $masters = ExamMaster::where('created_by',Auth::user()->id)->get();
        return view('guru.exam.master',compact('masters'))->with('i');
    }

    public function store(Request $request)
    {
        ExamMaster::create([
            'name'       => $request->name,
            'created_by' => Auth::user()->id,
        ]);
        return back()->with('success','Data Exam Master Berhasil Ditambah');
    }

    public function update(Request $request, $id)
    {
        ExamMaster::find($id)->update([
            'name'       => $request->name,
            'created_by' => Auth::user()->id,
        ]);
        return back()->with('success','Data Exam Master Berhasil Diubah');
    }

    public function destroy($id)
    {
        ExamMaster::find($id)->delete();
        return back()->with('success','Data Exam Master Berhasil Dihapus');
    }
}

resources/views/guru/exam/event-select.blade.php
@extends('template.app')
@section('content')
  <div class="col-md-6 col-sm-6  ">
    <div class="x_panel">
      <div class="x_title">
        <h2>Select Data Event</h2>
        <ul class="nav navbar-right panel_toolbox">
          <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
          </li>
          <li><a class="close-link"><i class="fa fa-close"></i></a>
          </li>
        </ul>
        <div class="clearfix"></div>
      </div>
      <div class="x_content">

        <form id="demo-form2" action="{{route('guru.exam.event.index')}}" method="GET" data-parsley-validate class="form-horizontal form-label-left">
            @csrf
            <div class="item form-group">
                <label class="col-form-label col-md-3 col-sm-3 label-align" for="year">Tahun <span class="required">*</span>
                </label>
                <div class="col-md-9 col-sm-9 ">
                    <select name="year" id="year" class="form-control">
                        @for ($i=(Carbon\Carbon::now()->year+1); $i>=2000; $i--)
                          <option value="{{$i}}" @selected(date("Y") == $i)>{{$i}}</option>
                        @endfor
                    </select>
                </div>
            </div>
            <div class="item form-group">
                <label class="col-form-label col-md-3 col-sm-3 label-align" for="month">Bulan <span class="required">*</span>
                </label>
                <div class="col-md-9 col-sm-9 ">
                  <select name="month" id="month" class="form-control">
                    <option value="01"@selected(date("m") == 1)>Januari</option>
                    <option value="02"@selected(date("m") == 2)>Februari</option>
                    <option value="03"@selected(date("m") == 3)>Maret</option>
                    <option value="04"@selected(date("m") == 4)>April</option>
                    <option value="05"@selected(date("m") == 5)>Mei</option>
                    <option value="06"@selected(date("m") == 6)>Juni</option>
                    <option value="07"@selected(date("m") == 7)>Juli</option>
                    <option value="08"@selected(date("m") == 8)>Agustus</option>
                    <option value="09"@selected(date("m") == 9)>September</option>
                    <option value="10"@selected(date("m") == 10)>Oktober</option>
                    <option value="11"@selected(date("m") == 11)>November</option>
                    <option value="12"@selected(date("m") == 12)>Desember</option>
                  </select>                
                </div>
            </div>
            <div class="ln_solid"></div>
            <div class="item form-group">
                <div class="col-md-12">
                    <button type="submit" class="btn btn-info"  style="float: right;">Submit</button>
                    <button type="button" class="btn btn-secondary"  style="float: right;" data-dismiss="modal">Close</button>
                </div>
            </div>
        </form>

      </div>
    </div>
  </div>
@endsection

resources/views/guru/exam/exam-select.blade.php
@extends('template.app')
@section('content')
<div class="col-md-6 col-sm-6  ">
    <div class="x_panel">
      <div class="x_title">
        <h2>Select Data Exam</h2>
        <ul class="nav navbar-right panel_toolbox">
          <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
          </li>
          <li><a class="close-link"><i class="fa fa-close"></i></a>
          </li>
        </ul>
        <div class="clearfix"></div>
      </div>
      <div class="x_content">

      <form id="demo-form2" action="{{route('guru.exam.exam.index')}}" method="GET" data-parsley-validate class="form-horizontal form-label-left">
            @csrf
            <div class="item form-group">
                <label class="col-form-label col-md-3 col-sm-3 label-align" for="year">Tahun <span class="required">*</span>
                </label>
                <div class="col-md-9 col-sm-9 ">
                    <select name="year" id="year" class="form-control">
                        @for ($i=(Carbon\Carbon::now()->year+1); $i>=2000; $i--)
                          <option value="{{$i}}" @selected(date("Y") == $i)>{{$i}}</option>
                        @endfor
                    </select>
                </div>
            </div>
            <div class="item form-group">
                <label class="col-form-label col-md-3 col-sm-3 label-align" for="month">Bulan <span class="required">*</span>
                </label>
                <div class="col-md-9 col-sm-9 ">
                  <select name="month" id="month" class="form-control">
                    <option value="01"@selected(date("m") == 1)>Januari</option>
                    <option value="02"@selected(date("m") == 2)>Februari</option>
                    <option value="03"@selected(date("m") == 3)>Maret</option>
                    <option value="04"@selected(date("m") == 4)>April</option>
                    <option value="05"@selected(date("m") == 5)>Mei</option>
                    <option value="06"@selected(date("m") == 6)>Juni</option>
                    <option value="07"@selected(date("m") == 7)>Juli</option>
                    <option value="08"@selected(date("m") == 8)>Agustus</option>
                    <option value="09"@selected(date("m") == 9)>September</option>
                    <option value="10"@selected(date("m") == 10)>Oktober</option>
                    <option value="11"@selected(date("m") == 11)>November</option>
                    <option value="12"@selected(date("m") == 12)>Desember</option>
                  </select>                
                </div>
            </div>
            <div class="ln_solid"></div>
            <div class="item form-group">
                <div class="col-md-12">
                    <button type="submit" class="btn btn-info"  style="float: right;">Submit</button>
                    <button type="button" class="btn btn-secondary"  style="float: right;" data-dismiss="modal">Close</button>
                </div>
            </div>
        </form>

      </div>
    </div>
  </div>
@endsection

resources/views/guru/exam/master.blade.php
@extends('template.app')
@section('content')
    <div class="">
        <div class="page-title">
            <div class="title_left">
                <h4>Exam</h4>
            </div>
        </div>

        <div class="x_content bs-example-popovers">
           
        </div>
        <div class="clearfix"></div>
        <div class="row">
            <div class="col-md-12 col-sm-12 ">
                <div class="x_panel">
                <div class="x_title">
                    <h2>List Data Exam Master</h2>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="card-box" style="padding-right:10px">
                                <button  type="button"  class="btn btn-info" data-toggle="modal" data-target="#modal-lg" style="float:right;" >
                                <i class="fa fa-plus"></i> Tambah  Exam Master
                                </button>
                            </div>
                        </div>
                        <div class="col-sm-12">
                            <div class="card-box table-responsive">
                                <table id="datatable" class="table table-striped table-bordered" style="width:100%">
                                    <thead>
                                        <tr>
                                            <th style="text-align: center;" width="5%">No</th>
                                            <th style="text-align: center;">Title</th>
                                            <th style="text-align: center;">Jumlah Soal</th>
                                            <th style="text-align: center;">Created By</th>
                                            <th style="text-align: center; width:22%">Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach ($masters as $master)
                                        <tr>
                                            <td style="text-align: center;">{{++$i}}</td>
                                            <td style="text-align: center;">{{$master->name}}</td>
                                            <td style="text-align: center;">{{$master->question->count()}} Soal</td>
                                            <td style="text-align: center;">{{$master->user->name}}</td>
                                            <td style="text-align: center;">
                                                <div class="d-flex justify-content-between align-items-center">
                                                    <a href="{{ route('guru.exam.question.index', ['master_id' => $master->id]) }}">
                                                        <button type="button" class="btn btn-secondary"><i class="fa fa-folder"></i> Soal</button>
                                                    </a>
                                                    <button type="button" class="btn btn-warning text-white"  data-toggle="modal" data-target="#modal-edit-lg{{$master->id}}"><i class="fa fa-pencil"></i> Ubah</button>
                                                    <form action="{{route('guru.exam.master.destroy', $master->id)}}" method="POST">
                                                        @csrf
                                                        @method('DELETE')
                                                        <button type="submit" class="btn btn-danger"><i class="fa fa-trash"></i> Hapus</button>
                                                    </form>
                                                </div>
                                            </td>
                                        </tr>
                                        @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <x-box-modal-large>
        @slot('title') Tambah Exam Master @endslot
        @slot('body')
            <form id="demo-form2" action="{{route('guru.exam.master.store')}}" method="POST" data-parsley-validate class="form-horizontal form-label-left">
                @csrf
                <div class="item form-group">
                    <label class="col-form-label col-md-3 col-sm-3 label-align" for="nama">Title <span class="required">*</span></label>
                    <div class="col-md-9 col-sm-9 ">
                        <input type="text" id="name" name="name" required="required" class="form-control ">
                    </div>
                </div>
                <div class="ln_solid"></div>
                <div class="item form-group">
                    <div class="col-md-12">
                        <button type="submit" class="btn btn-info"  style="float: right;">Submit</button>
                        <button type="button" class="btn btn-secondary"  style="float: right;" data-dismiss="modal">Close</button>
                    </div>
                </div>
            </form>
        @endslot
    </x-box-modal-large>

    @foreach ($masters as $master)
        <x-box-modal-edit-large id="{{$master->id}}">
            @slot('title') Edit Exam Master @endslot
            @slot('body')
                <form id="demo-form2" action="{{route('guru.exam.master.update',$master->id)}}" method="POST" data-parsley-validate class="form-horizontal form-label-left">
                    @csrf
                    @method('PUT')
                    <div class="item form-group">
                        <label class="col-form-label col-md-3 col-sm-3 label-align" for="nama">Title <span class="required">*</span>
                        </label>
                        <div class="col-md-9 col-sm-9 ">
                            <input type="link" id="name" name="name" required="required" class="form-control " value="{{$master->name}}">
                        </div>
                    </div>
                    <div class="ln_solid"></div>
                    <div class="item form-group">
                        <div class="col-md-12">
                            <button type="submit" class="btn btn-info"  style="float: right;">Submit</button>
                            <button type="button" class="btn btn-secondary"  style="float: right;" data-dismiss="modal">Close</button>
                        </div>
                    </div>
                </form>
            @endslot
        </x-box-modal-edit-large>
    @endforeach
@endsection