routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('login');
});

Route::get('/dashboard', function () {
    return view('dashboard');
});


Auth::routes();

// Route::middleware(['auth','user-role:Admin'])->group(function()
Route::prefix('admin')->middleware(['auth', 'user-role:Admin'])->as('admin.')->group(function ()
    {
    Route::get("home",[App\Http\Controllers\HomeController::class, 'adminHome'])->name("home");

    Route::prefix('kelompok')->as('kelompok.')->group(function ()
    {
        Route::get("select",[App\Http\Controllers\UserManagement\KelompokController::class,'select'])->name('select');
        Route::resource("index",App\Http\Controllers\UserManagement\KelompokController::class);
    });

    Route::prefix('siswa')->as('siswa.')->group(function ()
    {
        Route::get("select",[App\Http\Controllers\UserManagement\SiswaController::class,'select'])->name('select');
        Route::resource("index",App\Http\Controllers\UserManagement\SiswaController::class);
    });

    Route::resource("guru",App\Http\Controllers\UserManagement\GuruController::class);
    Route::resource("kelas",App\Http\Controllers\UserManagement\KelasController::class);
    
    Route::prefix('materi')->as('materi.')->group(function ()
    {
        Route::get("dokumen/select",[App\Http\Controllers\Admin\Materi\DokumenController::class,'select'])->name('dokumen.select');
        Route::resource("dokumen",App\Http\Controllers\Admin\Materi\DokumenController::class);
        Route::get("youtube/select",[App\Http\Controllers\Admin\Materi\YoutubeController::class,'select'])->name('youtube.select');
        Route::resource("youtube",App\Http\Controllers\Admin\Materi\YoutubeController::class);
        
    });

    Route::prefix('exam')->as('exam.')->group(function ()
    {
        Route::resource("master",App\Http\Controllers\Admin\Exam\MasterController::class);
        Route::resource("question",App\Http\Controllers\Admin\Exam\QuestionController::class);
        Route::resource("event",App\Http\Controllers\Admin\Exam\EventController::class);
        Route::get("event-select",[App\Http\Controllers\Admin\Exam\EventController::class,'select'])->name('event.select');
        Route::resource("exam",App\Http\Controllers\Admin\Exam\ExamController::class);
        Route::get("exam-select",[App\Http\Controllers\Admin\Exam\ExamController::class,'select'])->name('exam.select');
    });
});

// Route Guru
Route::prefix('guru')->middleware(['auth', 'user-role:Guru'])->as('guru.')->group(function ()
{
    Route::get("home",[App\Http\Controllers\HomeController::class, 'guruHome'])->name("home");

    Route::prefix('exam')->as('exam.')->group(function ()
    {
        Route::resource("master",App\Http\Controllers\Guru\Exam\MasterController::class);
        Route::resource("question",App\Http\Controllers\Guru\Exam\QuestionController::class);
        Route::resource("event",App\Http\Controllers\Guru\Exam\EventController::class);
        Route::get("event-select",[App\Http\Controllers\Guru\Exam\EventController::class,'select'])->name('event.select');
        Route::resource("exam",App\Http\Controllers\Guru\Exam\ExamController::class);
        Route::get("exam-select",[App\Http\Controllers\Guru\Exam\ExamController::class,'select'])->name('exam.select');
    });

    Route::prefix('materi')->as('materi.')->group(function ()
    {
        Route::get("dokumen/select",[App\Http\Controllers\Guru\Materi\DokumenController::class,'select'])->name('dokumen.select');
        Route::resource("dokumen",App\Http\Controllers\Guru\Materi\DokumenController::class);
        Route::get("youtube/select",[App\Http\Controllers\Guru\Materi\YoutubeController::class,'select'])->name('youtube.select');
        Route::resource("youtube",App\Http\Controllers\Guru\Materi\YoutubeController::class);
    });
});
// Route Siswa
Route::prefix('siswa')->middleware(['auth', 'user-role:Siswa'])->as('siswa.')->group(function ()
{
    Route::get("home",[App\Http\Controllers\HomeController::class, 'siswaHome'])->name("home");
    Route::resource("exam",App\Http\Controllers\Siswa\ExamController::class);
    Route::get("exam-select",[App\Http\Controllers\Siswa\ExamController::class,'select'])->name('exam.select');

    Route::prefix('materi')->as('materi.')->group(function ()
    {
        Route::resource("dokumen",App\Http\Controllers\Siswa\Materi\DokumenController::class);
        Route::resource("youtube",App\Http\Controllers\Siswa\Materi\YoutubeController::class);
    });
});

resources/views/template/app.blade.php
<!DOCTYPE html>
<html lang="en">
    @include('template.head')
    <body class="nav-md">
        <div class="container body">
            <div class="main_container">

                @include('template.sidebar')

                @include('template.header')

                <div class="right_col" role="main">

                    {{-- MAIN CONTENT --}}
                    <div class="x_content bs-example-popovers">
                        @if(session('success'))
                            <div class="alert alert-success alert-dismissible " role="alert">
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span>
                                </button>
                                <strong>{{ session('success') }}</strong>
                            </div>
                        @endif
                        @if ($errors->any())
                            <div class="alert alert-danger alert-dismissible " role="alert">
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span>
                                </button>
                                    @foreach ($errors->all() as $error)
                                        <strong>- {{ $error}}</strong> <br>
                                    @endforeach
                            </div>
                        @endif
                    </div>

                    @yield('content') 
                
                </div>
            </div>
        </div>
        @include('template.footer')
        @include('template.script')
    </body>
</html>

resources/views/template/editor-one.blade.php
@push('js')
    <script>
        $('#editor-one').on('input', function() {
            // Mendapatkan konten editor
            var content = $(this).html();
            // Mengatur nilai textarea tersembunyi dengan konten yang diperbarui
            $('#deskripsi').val(content);
        });

        // Submit form
        $('form').submit(function() {
            // Mendapatkan konten editor
            var content = $('#editor-one').html();
            // Mengatur nilai textarea tersembunyi dengan konten yang diperbarui
            $('#deskripsi').val(content);
            return true;
        });
    </script>

    <script>
        $('#edit_editor-one').on('input', function() {
            // Mendapatkan konten editor
            var content = $(this).html();
            // Mengatur nilai textarea tersembunyi dengan konten yang diperbarui
            $('#edit_deskripsi').val(content);
        });

        // Submit form
        $('form').submit(function() {
            // Mendapatkan konten editor
            var content = $('#edit_editor-one').html();
            // Mengatur nilai textarea tersembunyi dengan konten yang diperbarui
            $('#edit_deskripsi').val(content);
            return true;
        });
    </script>
@endpush

resources/views/template/footer.blade.php
<footer>
    <div class="pull-right">
        KELOMPOK BELAJAR SISWA by <a href="https://colorlib.com">Teknik Informatika POLITEKNIK NEGERI INDRAMAYU</a>
    </div>
    <div class="clearfix"></div>
</footer>

resources/views/template/head.blade.php
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{{asset('images/favicon.ico')}}" type="image/ico" />

    <title>Kelompok Belajar</title>

    <link href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css">
    <!-- Datatables -->
    <link href="{{asset('vendors/datatables.net-bs/css/dataTables.bootstrap.min.css')}}" rel="stylesheet">
    <link href="{{asset('vendors/datatables.net-buttons-bs/css/buttons.bootstrap.min.css')}}" rel="stylesheet">
    <link href="{{asset('vendors/datatables.net-fixedheader-bs/css/fixedHeader.bootstrap.min.css')}}" rel="stylesheet">
    <link href="{{asset('vendors/datatables.net-responsive-bs/css/responsive.bootstrap.min.css')}}" rel="stylesheet">
    <link href="{{asset('vendors/datatables.net-scroller-bs/css/scroller.bootstrap.min.css')}}" rel="stylesheet">

    <!-- Bootstrap -->
    <link href="{{asset('vendors/bootstrap/dist/css/bootstrap.min.css')}}" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="{{asset('vendors/font-awesome/css/font-awesome.min.css')}}" rel="stylesheet">
    <!-- NProgress -->
    <link href="{{asset('vendors/nprogress/nprogress.css')}}" rel="stylesheet">
    <!-- iCheck -->
    <link href="{{asset('vendors/iCheck/skins/flat/green.css')}}" rel="stylesheet">
    
    <!-- bootstrap-wysiwyg -->
	<link href="{{asset('vendors/google-code-prettify/bin/prettify.min.css')}}" rel="stylesheet">

    <!-- Select2 -->
	<link href="{{asset('vendors/select2/dist/css/select2.min.css')}}" rel="stylesheet">
	<!-- Switchery -->
	<link href="{{asset('vendors/switchery/dist/switchery.min.css')}}" rel="stylesheet">
	<!-- starrr -->
	<link href="{{asset('vendors/starrr/dist/starrr.css')}}" rel="stylesheet">
	<!-- bootstrap-daterangepicker -->
	<link href="{{asset('vendors/bootstrap-daterangepicker/daterangepicker.css')}}" rel="stylesheet">

    <!-- Custom Theme Style -->
    <link href="{{asset('build/css/custom.min.css')}}" rel="stylesheet">
</head>

resources/views/template/header.blade.php
<!-- top navigation -->
<div class="top_nav">
    <div class="nav_menu">
        <div class="nav toggle">
            <a id="menu_toggle"><i class="fa fa-bars"></i></a>
        </div>
        <nav class="nav navbar-nav">
            <ul class=" navbar-right">
                <li class="nav-item dropdown open" style="padding-left: 15px;">
                    <a href="javascript:;" class="user-profile dropdown-toggle" aria-haspopup="true" id="navbarDropdown" data-toggle="dropdown" aria-expanded="false">
                        <img src="{{asset('images/img.jpg')}}" alt="">{{Auth::user()->name}}
                    </a>
                    <div class="dropdown-menu dropdown-usermenu pull-right" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item"  href="javascript:;"> Profile</a>
                        <a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();" <i class="fa fa-sign-out pull-right"></i> Log Out</a>
                        <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                            @csrf
                        </form>               
                    </div>
                </li>
            </ul>
        </nav>
    </div>
</div>
<!-- /top navigation -->

resources/views/template/script.blade.php
    <!-- jQuery -->
    <script src="{{asset('vendors/jquery/dist/jquery.min.js')}}"></script>
    <!-- Bootstrap -->
    <script src="{{asset('vendors/bootstrap/dist/js/bootstrap.bundle.min.js')}}"></script>
    <!-- FastClick -->
    <script src="{{asset('vendors/fastclick/lib/fastclick.js')}}"></script>

    <!-- bootstrap-wysiwyg -->
	<script src="{{asset('vendors/bootstrap-wysiwyg/js/bootstrap-wysiwyg.min.js')}}"></script>
	<script src="{{asset('vendors/jquery.hotkeys/jquery.hotkeys.js')}}"></script>
	<script src="{{asset('vendors/google-code-prettify/src/prettify.js')}}"></script>


    <!-- Datatables -->
    <script src="{{asset('vendors/datatables.net/js/jquery.dataTables.min.js')}}"></script>
    <script src="{{asset('vendors/datatables.net-bs/js/dataTables.bootstrap.min.js')}}"></script>

    <!-- Select2 -->
	<script src="{{asset('vendors/select2/dist/js/select2.full.min.js')}}"></script>

    <!-- Custom Theme Scripts -->
    <script src="{{asset('build/js/custom.min.js')}}"></script>

    <script>
        setTimeout(function() {
            $('.alert').fadeOut('fast');
        }, 3000); // 300 milidetik atau 3 detik
    </script>

    @stack('js');

resources/views/template/sidebar.blade.php
<div class="col-md-3 left_col">
    <div class="left_col scroll-view">
        <div class="navbar nav_title" style="border: 0;">
            <a href="index.html" class="site_title"><span>Kelompok Belajar</span></a>
        </div>

        <div class="clearfix"></div>

        <!-- menu profile quick info -->
        <div class="profile clearfix">
            <div class="profile_pic">
                <img src="{{asset('images/img.jpg')}}" alt="..." class="img-circle profile_img">
            </div>
            <div class="profile_info">
                <span>Welcome,</span>
                <h2>{{Auth::user()->name}}</h2>
            </div>
        </div>
        <!-- /menu profile quick info -->

        <br />

        <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
            <div class="menu_section">
                <h3>Menu</h3>
                <ul class="nav side-menu">
                    <li><a><i class="fa fa-home"></i> Home <span class="fa fa-chevron-down"></span></a>
                        <ul class="nav child_menu">
                            <li><a href="{{route('login')}}">Dashboard</a></li>
                        </ul>
                    </li>
                    <li><a><i class="fa fa-newspaper-o"></i>Try Out<span class="fa fa-chevron-down"></span></a>
                        <ul class="nav child_menu">
                            @if(Auth::user()->role == 'Admin')
                                <li><a href="{{route('admin.exam.master.index')}}">Master</a></li>
                                <li><a href="{{route('admin.exam.event.select')}}">Event</a></li>
                                <li><a href="{{route('admin.exam.exam.select')}}">Exam</a></li>
                            @elseif(Auth::user()->role == 'Guru')
                                <li><a href="{{route('guru.exam.master.index')}}">Master</a></li>
                                <li><a href="{{route('guru.exam.event.select')}}">Event</a></li>
                                <li><a href="{{route('guru.exam.exam.select')}}">Exam</a></li>
                            @else
                                <li><a href="{{route('siswa.exam.select')}}">Exam</a></li>
                            @endif
                        </ul>
                    </li>
                    <li><a><i class="fa fa-book"></i> Materi<span class="fa fa-chevron-down"></span></a>
                        <ul class="nav child_menu">
                            @if(Auth::user()->role == 'Admin')
                                <li><a href="{{route('admin.materi.dokumen.select')}}">Dokumen</a></li>
                                <li><a href="{{route('admin.materi.youtube.select')}}">Youtube</a></li>
                            @elseif(Auth::user()->role == 'Guru')
                                <li><a href="{{route('guru.materi.dokumen.select')}}">Dokumen</a></li>
                                <li><a href="{{route('guru.materi.youtube.select')}}">Youtube</a></li>
                            @else
                                <li><a href="{{route('siswa.materi.dokumen.index')}}">Dokumen</a></li>
                                <li><a href="{{route('siswa.materi.youtube.index')}}">Youtube</a></li>
                            @endif
                        </ul>
                    </li>

                    @if(Auth::user()->role == 'Admin')
                    <li><a><i class="fa fa-users"></i> User Management <span class="fa fa-chevron-down"></span></a>
                        <ul class="nav child_menu">
                            <li><a href="{{route('admin.kelompok.select')}}">Kelompok</a></li>
                            <li><a href="{{route('admin.siswa.select')}}">Siswa</a></li>
                            <li><a href="{{route('admin.guru.index')}}">Guru</a></li>
                            <li><a href="{{route('admin.kelas.index')}}">Kelas</a></li>
                        </ul>
                    </li>
                    @endif
                </ul>
            </div>
        </div>
    </div>
</div>